name: Build

on: [push]

env:
  BUILD_TYPE: Release
  CC: gcc-10
  CXX: g++-10

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Configure ninja
      shell: bash
      run: sudo apt-get install ninja-build

    - name: Configure vcpkg
      working-directory: ${{runner.workspace}}
      shell: bash
      run: |
        git clone https://github.com/Microsoft/vcpkg.git
        ./vcpkg/bootstrap-vcpkg.sh -disableMetrics
        ./vcpkg/vcpkg integrate install
        ./vcpkg/vcpkg install spdlog fmt sfml sdl2

    - name: Create build environment
      shell: bash
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure CMake
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: cmake $GITHUB_WORKSPACE -GNinja -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DENABLE_TESTING=ON -DCMAKE_TOOLCHAIN_FILE=${{runner.workspace}}/vcpkg/scripts/buildsystems/vcpkg.cmake

    - name: Build
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: cmake --build . --config $BUILD_TYPE --target gameboiadvance_tests -- -j $(nproc)

    - name: Test
      working-directory: $GITHUB_WORKSPACE/build
      shell: bash
      run: ctest -C $BUILD_TYPE
